---
title: 'Berlin''s Demographic and Political Landscape (Also: Choropleth Maps!)'
author: Gershom Tripp
date: '2018-12-12'
slug: berlin-s-demographic-and-political-landscape-also-choropleth-maps
categories: []
tags:
  - Berlin
  - Dataviz
  - R
  - Maps
  - Politics
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

```{r load_packages, include=FALSE}
library(tidyverse)
library(ggmap)
library(maps)
library(mapdata)
library(ggstance)
library(gridExtra)
library(readr)
library(httr)
```


```{r load_data, include=FALSE}
# load cleaned yelp data (found here: https://github.com/GershTri/yelp-r)
load("datasets/yelp/berlin_yelp_sf_info.rda")
```

```{r reduce_restructure_yelp_df, include=FALSE}
# extract categories from categories.title.1
cat_titles1 <- yelp_df %>% 
    filter(!is.na(categories.title.1)) %>% 
    select(-categories.title) %>% 
    rename(categories.title = categories.title.1)

# extract categories from categories.title.2
cat_titles2 <- yelp_df %>% 
    filter(!is.na(categories.title.2)) %>% 
    select(-categories.title) %>% 
    rename(categories.title = categories.title.2)

# recombind above data frames with yelp_df and remove unneeded variables
yelp_df <- bind_rows(yelp_df, cat_titles1, cat_titles2) %>% 
    select(-c(alias, image_url, is_closed, url, starts_with("categories.alias"),
              starts_with("location.address"), starts_with("location.disp"),
              phone, display_phone, starts_with("categories.title."),
              location.country
              )
           )

rm(cat_titles1, cat_titles2)
```

Intro here.










## Some Demographics

```{r plot_population_density}
density_breaks <- sort(round(info_district_df$pop_dense))[c(2, 6, 8, 11, 12)]

ggplot(sf_districts) +
    geom_sf(aes(fill = info_district_df$pop_dense)) + 
    scale_fill_viridis_c(breaks = density_breaks) +
    labs(title = "Population Density (People per km^2)", fill = "density") +
    theme(
        panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5)
    )

rm(density_breaks)
```

```{r plot_foreign_residents}
foreign_breaks <- sort(info_district_df$foreign)[c(2, 8, 10, 11, 12)]

ggplot(sf_districts) +
    geom_sf(aes(fill = info_district_df$foreign)) + 
    scale_fill_viridis_c(breaks = foreign_breaks) +
    labs(title = "Proportion of Foreign Residents", fill = "proportion") +
    theme(
        panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5)
    )

rm(foreign_breaks)
```

```{r plot_average_age}
age_breaks <- sort(info_district_df$avg_age)[c(1, 3, 5, 9, 12)]

ggplot(sf_districts) +
    geom_sf(aes(fill = info_district_df$avg_age)) + 
    scale_fill_viridis_c(breaks = age_breaks, direction = -1) +
    labs(title = "Average Age of Residents", fill = "mean") +
    theme(
        panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5)
    )

rm(age_breaks)
```


```{r modify_pol_parties, include=FALSE}
# sum the rows to get proportions
pol_parties$Sum <- rowSums(pol_parties[,2:8])

# translate German and calculate proportion
pol_parties <- pol_parties %>% 
    rename(Rest = Sonstige) %>% 
    mutate(SPD = SPD/Sum,
           CDU = CDU/Sum,
           Grüne = Grüne/Sum,
           Linke = Linke/Sum,
           AfD = AfD/Sum,
           FDP = FDP/Sum,
           Rest = Rest/Sum
           ) %>% 
    select(-Sum) %>% 
    rename(`Die Grünen` = Grüne, `Die Linke` = Linke)

# tidy data frame
pol_parties <- pol_parties %>%
    gather(Party, Proportion, -District) %>% 
    arrange(District)

pol_parties$District <- factor(pol_parties$District,
                               ordered = T,
                               levels = rev(unique(pol_parties$District))
                               )

pol_parties$Party <- factor(pol_parties$Party,
                            ordered = T,
                            levels = c("Die Linke", "SPD", "Die Grünen",
                                       "CDU", "FDP", "AfD", "Rest"
                                       )
                            )

# remove duplicated neukölln
pol_parties <- pol_parties %>% distinct()

# include size scale
dom_berlin <- pol_parties %>% 
    filter(District == "Berlin") %>% 
    select(Party, Proportion)

dom_berlin$Proportion <- c(10, 8.5, 6, 6, 4, 2.5, 1)

dom_berlin <- dom_berlin %>% 
    mutate(Proportion = as.integer(Proportion)) %>% 
    rename(`Dominance - Berlin` = Proportion)

pol_parties <- full_join(pol_parties, dom_berlin, by = "Party")

# manually modify Die Grünen and Die Linke in Berlin to deal with overlap
pol_parties[3, "Dominance - Berlin"] <- 7
pol_parties[4, "Dominance - Berlin"] <- 6


# rank according to afd dominance
afd_dom <- pol_parties %>%
    filter(Party == "AfD") %>% 
    arrange(Proportion) %>% 
    filter(District != "Berlin") %>%
    mutate(afd_rank = 0:11) %>% 
    select(-(2:4))

afd_dom <- rbind(afd_dom, c("Berlin", 12)) %>% 
    mutate(afd_rank = as.integer(afd_rank))

pol_parties <- full_join(pol_parties, afd_dom, by = "District")

pol_parties <- pol_parties %>%
    mutate(District = factor(District,
                             levels = arrange(pol_parties, afd_rank) %>% 
                                 .$District %>% 
                                 unique()
                             )
           )
```


```{r plot_political_parties, fig.height=7, fig.width=6.5}
ggplot(pol_parties, aes(y = District,
                        x = Proportion,
                        group = District,
                        color = Party
                        )
       ) +
    geom_point(size = pol_parties$`Dominance - Berlin`) +
    scale_color_manual(values = c("purple", "red", "#229954", "black",
                                  "#F7DC6F", "#3498DB", "grey"
                                  )
                       ) +
    theme_minimal() +
    theme(panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          plot.title = element_text(hjust = 0.5)
          ) + 
    ggtitle("Party Dominance by District")
```

```{r plot_afd_representation}
afd_district <- pol_parties %>% 
    filter(Party == "AfD", District != "Berlin")


ggplot(sf_districts) +
    geom_sf(aes(fill = afd_district$Proportion)) + 
    scale_fill_viridis_c() +
    labs(title = "AfD Representation by District", fill = "proportion") +
    theme(
        panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5)
    )
```